### ISSUE TITLE
Time Series Forecasting

### ISSUE THREAD

**Issue by namitabagri** [SnowScriptWinterOfCode/ML-Models#2]
### Time Series Forecasting

**Problem Statement:**  Use a dataset with 2 months of data on One Drive user activities to predict 5 years of storage capacity.
**Steps :** 

- Generate dataset with prompt engineering and use of OpenAI API 
- Train conventional time series models - ARIMA, SARIMA etc.
- Get Predictions
- Introduce exogenous variables to the dataset  and train model like ARIMAX and FB-PROPHET on it.
- Compare predictions of exogenous and standard feature utilizing models
- Get results
- Improve upon the results with ensemble methods.

**Comment by namitabagri** [comment]
@tejaswi0910 Please assign this issue to me, I would love to work on this project.

**Comment by tejaswi0910** [comment]
Thankyou for contributing ! Your PR is now merged.
