### ISSUE TITLE
Git clone issue in Windows OS due to special character in file names

### ISSUE THREAD

**Issue by ruchikapatro24** [SnowScriptWinterOfCode/ML-Models#20]
In the source code folder, there is a file named `Dataset->Movie Recommender` which creates problem during cloning the Git repo into local Windows OS.

In a GitHub repository, a file with a name containing "->" typically indicates the use of a symbolic link or symlink. Symbolic links are references to another file or directory, essentially creating a shortcut or alias. The "->" arrow is often used to visually represent the link between the original file/directory and the symlink.

For example, if you have a file named file1.txt and a symlink with the name file2.txt -> file1.txt, it means that accessing file2.txt will lead you to the contents of file1.txt. This can be useful for creating references to common files or directories without duplicating the actual data.

However, it's essential to note that symbolic links may not work as expected on all systems, and they might behave differently on Windows, macOS, and Linux. So, file names should not contain the special character "->", unless we are creating symlinks

The File name in the source code should not contain special characters, especially "->" character. It is misinterpreted by git as a Branch path. This issue is automatically handled in Linux or Mac OS.

**Comment by ruchikapatro24** [comment]
@tejaswi0910  @Nitya-Pasrija please assign this issue to me. I am working on this.

**Comment by tejaswi0910** [comment]
Assigning the issue to you, please go ahead and fix this!

**Comment by ruchikapatro24** [comment]
In a GitHub repository, a file with a name containing "->" typically indicates the use of a symbolic link or symlink. Symbolic links are references to another file or directory, essentially creating a shortcut or alias. The "->" arrow is often used to visually represent the link between the original file/directory and the symlink.

For example, if you have a file named `file1.txt` and a symlink with the name `file2.txt -> file1.txt`, it means that accessing `file2.txt` will lead you to the contents of `file1.txt`. This can be useful for creating references to common files or directories without duplicating the actual data.

However, it's essential to note that symbolic links may not work as expected on all systems, and they might behave differently on Windows, macOS, and Linux. So, file names should not contain the special character "->", unless we are creating symlinks
