### ISSUE TITLE
Covid19 Prediction

### ISSUE THREAD

**Issue by namitabagri** [SnowScriptWinterOfCode/ML-Models#28]
Predicting the daily number of confirmed COVID19 cases in various locations across the world

- Perform data analysis to identify the factors that impact the transmission rate of COVID-19.
- Analyze the the effect of COVID-19 in India. 
- Use XGBoost and Random Forest regressor as ensemble learning models as well as to predict the daily # of confirmed cases

**Comment by namitabagri** [comment]
Please assign this issue to me @tejaswi0910

**Comment by tejaswi0910** [comment]
closing the issue now
