### ISSUE TITLE
NLP Text Summarizer Project

### ISSUE THREAD

**Issue by praggyaverma** [SnowScriptWinterOfCode/ML-Models#3]
## NLP Text Summarizer Project

**Problem Statement** - Train and test a machine learning model to produce text summary using dataset from HuggingFace

**Comment by praggyaverma** [comment]
Hi moderator @tejaswi0910 please assign this issue to me, I would love to work on it!

**Comment by tejaswi0910** [comment]
Closing this issue, thankyou for contributing!
