### ISSUE TITLE
Psychosocial Balance of Student Analysis

### ISSUE THREAD

**Issue by acecoder7** [SnowScriptWinterOfCode/ML-Models#30]
This project aims to uncover correlations between depression levels, academic performance, and various lifestyle factors of a student life.
[Psychosocial Dimensions of Student Life](https://www.kaggle.com/datasets/mdismielhossenabir/psychosocial-dimensions-of-student-life) Dataset will be used . Focus on finding key patterns and training a accurate model for predicting depression level of a student.
This project not only addresses crucial mental health concerns but also contributes to enhancing student support systems and fostering a positive learning environment.

**Comment by acecoder7** [comment]
Hi @tejaswi0910 @Nitya-Pasrija i would like to work on this issue. Kindly assign this issue to me

**Comment by tejaswi0910** [comment]
Assigned the issue to you! Please make sure you are submitting the PR for the same before the contribution period ends!!
