### ISSUE TITLE
Text based emotion classifier

### ISSUE THREAD

**Issue by namitabagri** [SnowScriptWinterOfCode/ML-Models#7]
**Objective:** Build a model that can classify the emotions (e.g., happy, sad, angry) expressed in a given text input.

**Workflow:**

- Data Collection: Gather a dataset with text samples labeled with emotions. 

- Data Preprocessing: Clean and preprocess the text data. This includes tasks like tokenization, removing stopwords, and converting text to numerical representations (e.g., word embeddings).

- Model Selection and Training: Train a  machine learning or deep learning model for text classification (e.g., LSTM, Naive Bayes, or SVM). 

- Evaluation: Evaluate the model's performance using metrics

**Comment by namitabagri** [comment]
Please assign this issue to me  @tejaswi0910

**Comment by tejaswi0910** [comment]
Hey Namita! I am assigning this issue to you. Thankyou for contributing, please make sure that you are submitting a folder with the subfiles in it as a pull request. Kindly refer to the stock prediction folder as submitted by a contributor (The folder is including the files within it, making it easier to access)

**Comment by namitabagri** [comment]
Okay 👍,  will do that :)

**Comment by tejaswi0910** [comment]
Closing the issue! Thankyou for the contribution Namita
